version: "3.9"
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_pet
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Senha123!"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - pet_data:/var/opt/mssql
    restart: unless-stopped
volumes:
  pet_data: